package main

import (
	"context"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"
)

// Fixtures generated by the existing Better Auth scrypt/HMAC implementation.
const nodePasswordFixture = "00112233445566778899aabbccddeeff:67ac0d16c084a3955d28f0722d93e0314b727e0c595827af8e01799634b34f51154427ae3342aee9c8c82338495e8d545a8fb779cc18ce355c061dae042ff8f2"
const nodeCookieFixture = "test-session-token.F9GCGNzEbK7oKsuARlIX46cGPI1dyky8aVQnqxUXOpo%3D"

func TestBetterAuthPasswordCompatibility(t *testing.T) {
	for _, tt := range []struct {
		password, hash string
		valid          bool
	}{
		{"ＦluxMedia-测试", nodePasswordFixture, true},
		{"FluxMedia-测试", nodePasswordFixture, true},
		{"wrong", nodePasswordFixture, false},
		{"any", "malformed", false},
	} {
		actual, err := verifyPassword(context.Background(), tt.password, tt.hash)
		if err != nil || actual != tt.valid {
			t.Fatalf("valid=%v want=%v error=%v", actual, tt.valid, err)
		}
	}
	hash, err := hashPassword(context.Background(), "New-password")
	if err != nil {
		t.Fatal(err)
	}
	valid, err := verifyPassword(context.Background(), "New-password", hash)
	if err != nil || !valid {
		t.Fatal("new password cannot be verified")
	}
}
func TestBetterAuthCookieCompatibility(t *testing.T) {
	if got := verifySessionCookie(nodeCookieFixture, "test-auth-secret"); got != "test-session-token" {
		t.Fatal("existing signed cookie rejected")
	}
	for _, value := range []string{"test-session-token", nodeCookieFixture + "x", "%not-url-encoded", "other" + nodeCookieFixture} {
		if got := verifySessionCookie(value, "test-auth-secret"); got != "" {
			t.Fatal("forged cookie accepted")
		}
	}
	if got := verifySessionCookie(nodeCookieFixture, "different-secret"); got != "" {
		t.Fatal("wrong signing key accepted")
	}
	decoded, _ := url.PathUnescape(nodeCookieFixture)
	if signSessionToken("test-session-token", "test-auth-secret") != decoded {
		t.Fatal("new cookies incompatible with Node")
	}
}
func TestSessionCookieBoundary(t *testing.T) {
	b := backend{config: config{authURL: "https://media.example", authSecret: "test-auth-secret"}}
	r := httptest.NewRequest("GET", "https://media.example/api/auth/get-session", nil)
	r.AddCookie(&http.Cookie{Name: "better-auth.session_token", Value: nodeCookieFixture})
	if b.sessionToken(r) != "" {
		t.Fatal("HTTPS accepted unprefixed cookie")
	}
	r.AddCookie(&http.Cookie{Name: "__Secure-better-auth.session_token", Value: nodeCookieFixture})
	if b.sessionToken(r) != "test-session-token" {
		t.Fatal("HTTPS rejected secure cookie")
	}
}
func TestAuthRedirectValidation(t *testing.T) {
	b := backend{config: config{authURL: "https://media.example", trustedOrigins: []string{"https://admin.example"}}}
	for _, raw := range []string{"/dashboard", "https://media.example/dashboard", "https://admin.example/return", ""} {
		if _, err := b.safeRedirect(raw); err != nil {
			t.Errorf("valid redirect %q: %v", raw, err)
		}
	}
	for _, raw := range []string{"//evil.example", "javascript:alert(1)", "https://media.example@evil.example/", "https://user:password@media.example/", "http://media.example/", "https://media.example.evil.example/"} {
		if _, err := b.safeRedirect(raw); err == nil {
			t.Errorf("unsafe redirect allowed: %q", raw)
		}
	}
}
func TestJSONInputRejectsPrivilegeFieldsAndTrailingValues(t *testing.T) {
	for _, body := range []string{`{"name":"user","role":"super_admin"}`, `{"name":"user"} {}`, `not-json`} {
		r := httptest.NewRequest("POST", "/", strings.NewReader(body))
		var input struct {
			Name string `json:"name"`
		}
		if err := decodeBody(r, &input); err == nil {
			t.Errorf("unsafe input accepted: %s", body)
		}
	}
}
func TestSessionQueriesWithoutCookieDoNotNeedDatabase(t *testing.T) {
	b := backend{config: config{authSecret: "test-auth-secret", authURL: "http://localhost:3000"}}
	r := httptest.NewRequest("GET", "/api/session/current", nil)
	w := httptest.NewRecorder()
	if err := b.handleSession(w, r); err != nil {
		t.Fatal(err)
	}
	if w.Code != 200 || strings.TrimSpace(w.Body.String()) != "null" || !strings.Contains(w.Header().Get("Cache-Control"), "no-store") {
		t.Fatal("invalid anonymous session response")
	}
}

func TestEmailTokenIntegrityAndPurpose(t *testing.T) {
	b := backend{config: config{authSecret: "test-auth-secret"}}
	token, err := b.emailVerificationToken("test@gmail.com")
	if err != nil {
		t.Fatal(err)
	}
	email, err := b.verifiedEmailToken(token)
	if err != nil || email != "test@gmail.com" {
		t.Fatal("verification token rejected")
	}
	for _, value := range []string{token + "x", "none.e30.", nodeCookieFixture} {
		if _, err := b.verifiedEmailToken(value); err == nil {
			t.Fatal("invalid email token accepted")
		}
	}
}
func TestCanonicalRegistrationEmail(t *testing.T) {
	for raw, want := range map[string]string{" A.B+tag@gmail.com ": "ab@gmail.com", "name+tag@qq.com": "name@qq.com", "name@qq.com": "name@qq.com"} {
		if got := canonicalEmail(raw); got != want {
			t.Fatalf("canonical %q=%q want %q", raw, got, want)
		}
	}
	if err := validateRegistrationEmail("name@evil.example"); err == nil {
		t.Fatal("nonallowlisted email accepted")
	}
}
