package main

import (
	"context"
	"encoding/json"
	"fmt"
	"html"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/fluxmedia/fluxmedia/services/api-gateway/webui"
)

const (
	defaultPageLocale       = "en"
	localeCookieName        = "NEXT_LOCALE"
	appConfigPlaceholder    = "<!--app-config-->"
	routeMetaPlaceholder    = "<!--route-meta-->"
	defaultHTMLLangAttr     = `<html lang="en">`
	immutableAssetCache     = "public, max-age=31536000, immutable"
	publicFileCache         = "public, max-age=3600"
	pageTimeZoneReadTimeout = 2 * time.Second
)

var (
	pageLocales        = []string{"en", "zh"}
	sessionCookieNames = []string{"better-auth.session_token", "__Secure-better-auth.session_token"}
	// Pages that must never be indexed or cached by shared caches, matching the
	// robots.txt disallow list generated by the SPA build.
	privatePagePrefixes = []string{"/dashboard", "/sign-in", "/sign-up", "/forgot-password", "/reset-password"}
)

type goCompatibilityPrefixKey struct{}

// webApp serves the Vite SPA build: hashed assets, public files and the
// index.html shell for every localized page. It replaces the former Next.js
// proxy: locale prefix redirects, the dashboard session gate and the cache
// headers of auth pages keep the same contract.
type webApp struct {
	files    fs.FS
	index    string
	origin   string
	timeZone func(context.Context) string
}

func newWebApp(files fs.FS, origin string, timeZone func(context.Context) string) (*webApp, error) {
	index, err := fs.ReadFile(files, "index.html")
	if err != nil {
		return nil, fmt.Errorf("read web index.html: %w", err)
	}
	return &webApp{files: files, index: string(index), origin: strings.TrimRight(origin, "/"), timeZone: timeZone}, nil
}

// loadWebApp prefers an explicit FLUXMEDIA_WEB_DIST directory over the embedded
// build. A backend without either still serves every API route.
func (b *backend) loadWebApp() (*webApp, error) {
	var files fs.FS
	if b.config.webDistDir != "" {
		files = os.DirFS(b.config.webDistDir)
	} else if embedded, ok := webui.Dist(); ok {
		files = embedded
	} else {
		return nil, nil
	}
	origin := b.config.publicAppURL
	if origin == "" {
		origin = b.config.authURL
	}
	return newWebApp(files, origin, b.pageTimeZone)
}

// pageTimeZone resolves the deployment display time zone exposed to the SPA as
// runtime config; a settings outage degrades to the environment value.
func (b *backend) pageTimeZone(ctx context.Context) string {
	ctx, cancel := context.WithTimeout(ctx, pageTimeZoneReadTimeout)
	defer cancel()
	zone, err := b.settingString(ctx, "APP_TIME_ZONE", "UTC")
	if err != nil {
		b.logger.WarnContext(ctx, "page time zone setting unavailable", "error", err)
		zone = strings.TrimSpace(os.Getenv("APP_TIME_ZONE"))
	}
	return strings.TrimSpace(zone)
}

// handleFallback receives every request no API route matched. Backend
// namespaces keep the explicit not-migrated JSON contract; everything else is
// the web application.
func (b *backend) handleFallback(w http.ResponseWriter, r *http.Request) {
	if b.web == nil || isBackendNamespace(r.URL.Path) || r.Context().Value(goCompatibilityPrefixKey{}) != nil {
		b.handleNotMigrated(w, r)
		return
	}
	b.web.ServeHTTP(w, r)
}

func isBackendNamespace(p string) bool {
	for _, prefix := range []string{"/api", "/v1", "/v1beta", "/r", "/moderate", "/healthz", "/readyz", "/health", "/ready"} {
		if p == prefix || strings.HasPrefix(p, prefix+"/") {
			return true
		}
	}
	return false
}

func (a *webApp) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		w.Header().Set("Allow", "GET, HEAD")
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}
	cleaned := path.Clean("/" + r.URL.Path)
	if a.serveFile(w, r, cleaned) {
		return
	}
	locale, rest := splitPageLocale(cleaned)
	if locale == "" && (strings.HasPrefix(cleaned, "/static/") || path.Ext(cleaned) != "") {
		// Missing assets must not fall through to the HTML shell: browsers would
		// reject it as a script or image with a confusing MIME error.
		http.NotFound(w, r)
		return
	}
	private := isPrivatePage(rest)
	prefixed := locale != ""
	if !prefixed {
		locale = negotiatePageLocale(r)
	}
	if isDashboardPage(rest) && !hasSessionCookie(r) {
		callback := r.URL.EscapedPath()
		if r.URL.RawQuery != "" {
			callback += "?" + r.URL.RawQuery
		}
		noStore(w)
		http.Redirect(w, r, "/"+locale+"/sign-in?callbackUrl="+url.QueryEscape(callback), http.StatusTemporaryRedirect)
		return
	}
	if !prefixed {
		target := "/" + locale
		if cleaned != "/" {
			target += cleaned
		}
		if r.URL.RawQuery != "" {
			target += "?" + r.URL.RawQuery
		}
		if private {
			noStore(w)
		}
		http.Redirect(w, r, target, http.StatusTemporaryRedirect)
		return
	}
	a.serveIndex(w, r, locale, rest, private)
}

// serveFile serves a concrete file from the build. index.html is only ever
// rendered through serveIndex so its placeholders are always replaced.
func (a *webApp) serveFile(w http.ResponseWriter, r *http.Request, cleaned string) bool {
	name := strings.TrimPrefix(cleaned, "/")
	if name == "" || name == "index.html" || !fs.ValidPath(name) {
		return false
	}
	info, err := fs.Stat(a.files, name)
	if err != nil || info.IsDir() {
		return false
	}
	if strings.HasPrefix(name, "static/") {
		w.Header().Set("Cache-Control", immutableAssetCache)
	} else {
		w.Header().Set("Cache-Control", publicFileCache)
	}
	http.ServeFileFS(w, r, a.files, name)
	return true
}

func (a *webApp) serveIndex(w http.ResponseWriter, r *http.Request, locale, rest string, private bool) {
	config := map[string]string{}
	if a.timeZone != nil {
		if zone := a.timeZone(r.Context()); zone != "" {
			config["appTimeZone"] = zone
		}
	}
	// json.Marshal escapes <, > and & so the payload cannot close the script.
	payload, err := json.Marshal(config)
	if err != nil {
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}
	page := strings.Replace(a.index, defaultHTMLLangAttr, `<html lang="`+locale+`">`, 1)
	page = strings.Replace(page, appConfigPlaceholder, "<script>window.__FLUXMEDIA_CONFIG__="+string(payload)+"</script>", 1)
	page = strings.Replace(page, routeMetaPlaceholder, a.routeMeta(locale, rest, private), 1)

	if private {
		noStore(w)
	} else {
		w.Header().Set("Cache-Control", "no-cache")
	}
	if cookie, err := r.Cookie(localeCookieName); err != nil || cookie.Value != locale {
		http.SetCookie(w, &http.Cookie{Name: localeCookieName, Value: locale, Path: "/", SameSite: http.SameSiteLaxMode})
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Content-Length", strconv.Itoa(len(page)))
	w.WriteHeader(http.StatusOK)
	if r.Method != http.MethodHead {
		_, _ = w.Write([]byte(page))
	}
}

// routeMeta renders the address-dependent first-screen SEO tags. Site-wide
// tags are written into index.html at build time; the client replaces every
// data-route-meta tag once the route metadata resolves.
func (a *webApp) routeMeta(locale, rest string, private bool) string {
	suffix := rest
	if suffix == "/" {
		suffix = ""
	}
	pageURL := a.origin + "/" + locale + suffix
	ogLocale := "en_US"
	if locale == "zh" {
		ogLocale = "zh_CN"
	}
	var tags []string
	meta := func(attribute, key, content string) {
		tags = append(tags, `<meta `+attribute+`="`+key+`" content="`+html.EscapeString(content)+`" data-route-meta />`)
	}
	link := func(rel, href, hreflang string) {
		tag := `<link rel="` + rel + `" href="` + html.EscapeString(href) + `"`
		if hreflang != "" {
			tag += ` hreflang="` + hreflang + `"`
		}
		tags = append(tags, tag+` data-route-meta />`)
	}
	if private {
		meta("name", "robots", "noindex, nofollow")
	}
	meta("property", "og:locale", ogLocale)
	meta("property", "og:url", pageURL)
	meta("property", "og:image", a.origin+"/og-image.png")
	meta("name", "twitter:image", a.origin+"/og-image.png")
	link("canonical", pageURL, "")
	for _, l := range pageLocales {
		link("alternate", a.origin+"/"+l+suffix, l)
	}
	link("alternate", a.origin+"/"+defaultPageLocale+suffix, "x-default")
	return strings.Join(tags, "\n    ")
}

// splitPageLocale returns the supported locale prefix and the remaining path;
// an unprefixed path returns an empty locale.
func splitPageLocale(p string) (string, string) {
	for _, locale := range pageLocales {
		if p == "/"+locale {
			return locale, "/"
		}
		if strings.HasPrefix(p, "/"+locale+"/") {
			return locale, strings.TrimPrefix(p, "/"+locale)
		}
	}
	return "", p
}

func isDashboardPage(rest string) bool {
	return rest == "/dashboard" || strings.HasPrefix(rest, "/dashboard/")
}

func isPrivatePage(rest string) bool {
	for _, prefix := range privatePagePrefixes {
		if rest == prefix || strings.HasPrefix(rest, prefix+"/") {
			return true
		}
	}
	return false
}

func hasSessionCookie(r *http.Request) bool {
	for _, name := range sessionCookieNames {
		if cookie, err := r.Cookie(name); err == nil && cookie.Value != "" {
			return true
		}
	}
	return false
}

// negotiatePageLocale mirrors next-intl: a supported NEXT_LOCALE cookie wins,
// then the highest weighted supported Accept-Language entry, then English.
func negotiatePageLocale(r *http.Request) string {
	if cookie, err := r.Cookie(localeCookieName); err == nil && isPageLocale(cookie.Value) {
		return cookie.Value
	}
	type candidate struct {
		lang   string
		weight float64
	}
	var candidates []candidate
	for _, part := range strings.Split(r.Header.Get("Accept-Language"), ",") {
		tag, params, _ := strings.Cut(strings.TrimSpace(part), ";")
		weight := 1.0
		if q, ok := strings.CutPrefix(strings.TrimSpace(params), "q="); ok {
			parsed, err := strconv.ParseFloat(q, 64)
			if err != nil {
				continue
			}
			weight = parsed
		}
		primary, _, _ := strings.Cut(strings.ToLower(strings.TrimSpace(tag)), "-")
		if weight > 0 && isPageLocale(primary) {
			candidates = append(candidates, candidate{primary, weight})
		}
	}
	sort.SliceStable(candidates, func(i, j int) bool { return candidates[i].weight > candidates[j].weight })
	if len(candidates) > 0 {
		return candidates[0].lang
	}
	return defaultPageLocale
}

func isPageLocale(value string) bool {
	for _, locale := range pageLocales {
		if value == locale {
			return true
		}
	}
	return false
}
