import { requestGoBackendJson, type UntypedGoBackendJson } from "../../http/go-backend";
import { protectedAction, adminAction } from "../../safe-action";
import { addTicketMessageSchema, createTicketSchema, updateTicketStatusSchema } from "../schemas";
const go = <T>(path: string, init: RequestInit = {}) => requestGoBackendJson<T>(path, init);
export const createTicketAction=protectedAction.metadata({action:"support.createTicket"}).schema(createTicketSchema).action(async({parsedInput})=>go<UntypedGoBackendJson>("/api/support/tickets",{method:"POST",body:JSON.stringify(parsedInput)}));
export const addTicketMessageAction=protectedAction.metadata({action:"support.addTicketMessage"}).schema(addTicketMessageSchema).action(async({parsedInput})=>go<UntypedGoBackendJson>(`/api/support/tickets/${encodeURIComponent(parsedInput.ticketId)}/messages`,{method:"POST",body:JSON.stringify({content:parsedInput.content})}));
export const getAdminUnreadTicketCountAction=adminAction.metadata({action:"support.admin.getAdminUnreadTicketCount"}).action(async()=>go<{count:number}>("/api/support/tickets/unread-count"));
export const getMyUnreadTicketCountAction=protectedAction.metadata({action:"support.getMyUnreadTicketCount"}).action(async()=>go<{count:number}>("/api/support/tickets/unread-count"));
export const adminReplyTicketAction=adminAction.metadata({action:"support.admin.replyTicket"}).schema(addTicketMessageSchema).action(async({parsedInput})=>go<UntypedGoBackendJson>(`/api/support/tickets/${encodeURIComponent(parsedInput.ticketId)}/messages`,{method:"POST",body:JSON.stringify({content:parsedInput.content})}));
export const updateTicketStatusAction=adminAction.metadata({action:"support.admin.updateTicketStatus"}).schema(updateTicketStatusSchema).action(async({parsedInput})=>go<UntypedGoBackendJson>(`/api/support/tickets/${encodeURIComponent(parsedInput.ticketId)}/status`,{method:"PATCH",body:JSON.stringify({status:parsedInput.status})}));
