"use server";
import { cookies } from "next/headers";
import { protectedAction, adminAction } from "../../safe-action";
import { addTicketMessageSchema, createTicketSchema, updateTicketStatusSchema } from "../schemas";
async function go<T>(path:string, init:RequestInit={}):Promise<T>{const base=(process.env.GO_BACKEND_URL||"http://127.0.0.1:8080").replace(/\/$/u,"");const cookie=(await cookies()).getAll().map(c=>`${c.name}=${c.value}`).join("; ");const headers=new Headers(init.headers);if(init.body&&!headers.has("content-type"))headers.set("content-type","application/json");if(cookie)headers.set("cookie",cookie);const res=await fetch(base+path,{...init,headers,cache:"no-store"});const p=await res.json().catch(()=>null) as T & {error?:{message?:string}};if(!res.ok)throw new Error(p?.error?.message||`请求失败 (${res.status})`);return p;}
export const createTicketAction=protectedAction.metadata({action:"support.createTicket"}).schema(createTicketSchema).action(async({parsedInput})=>go<any>("/api/support/tickets",{method:"POST",body:JSON.stringify(parsedInput)}));
export const addTicketMessageAction=protectedAction.metadata({action:"support.addTicketMessage"}).schema(addTicketMessageSchema).action(async({parsedInput})=>go<any>(`/api/support/tickets/${encodeURIComponent(parsedInput.ticketId)}/messages`,{method:"POST",body:JSON.stringify({content:parsedInput.content})}));
export const getAdminUnreadTicketCountAction=adminAction.metadata({action:"support.admin.getAdminUnreadTicketCount"}).action(async()=>go<{count:number}>("/api/support/tickets/unread-count"));
export const getMyUnreadTicketCountAction=protectedAction.metadata({action:"support.getMyUnreadTicketCount"}).action(async()=>go<{count:number}>("/api/support/tickets/unread-count"));
export const adminReplyTicketAction=adminAction.metadata({action:"support.admin.replyTicket"}).schema(addTicketMessageSchema).action(async({parsedInput})=>go<any>(`/api/support/tickets/${encodeURIComponent(parsedInput.ticketId)}/messages`,{method:"POST",body:JSON.stringify({content:parsedInput.content})}));
export const updateTicketStatusAction=adminAction.metadata({action:"support.admin.updateTicketStatus"}).schema(updateTicketStatusSchema).action(async({parsedInput})=>go<any>(`/api/support/tickets/${encodeURIComponent(parsedInput.ticketId)}/status`,{method:"PATCH",body:JSON.stringify({status:parsedInput.status})}));
