/** 视频生成 UOL binding：任务状态与写入统一交给 Go backend。 */
import type { OperationContext, Principal } from "@repo/shared/uol";
import { bindExecute, bindOperationExecute, isExternalApiKeyPrincipal, OperationError } from "@repo/shared/uol";
import { videoGetGeminiOperation, videoGetInputs, videoListCapabilities, videoRequestAccountInputCleanup, type VideoGenerateInput } from "@repo/shared/uol/operations/video-generation";
import { requestGoJson, requestGoJsonForPrincipal } from "@/server/go-backend-client";
function principalRequest<T>(principal: Principal, path: string, init: RequestInit = {}): Promise<T> { return isExternalApiKeyPrincipal(principal) ? requestGoJsonForPrincipal(principal, path, init) : requestGoJson<T>(path, init); }
bindOperationExecute(videoListCapabilities, async (input, principal) => {
  if (principal.type !== "user" && principal.type !== "apiKey") {
    throw new OperationError("unauthenticated", "User identity required");
  }
  return principalRequest(principal, "/api/internal/video/capabilities", {
    method: "POST",
    body: JSON.stringify(input),
  });
});
bindOperationExecute(videoGetInputs, async (input, principal) => { if (principal.type !== "user" && principal.type !== "apiKey") throw new OperationError("unauthenticated", "User identity required"); const raw = await principalRequest<{ taskId: string; inputs?: unknown }>(principal, "/api/internal/video/inputs", { method: "POST", body: JSON.stringify(input) }); const value = (raw.inputs && typeof raw.inputs === "object" ? raw.inputs : {}) as Record<string, unknown>; const asset = (item: unknown) => { if (!item || typeof item !== "object") return undefined; const v = item as Record<string, unknown>; return typeof v.url === "string" && typeof v.mimeType === "string" ? { url: v.url, mimeType: v.mimeType } : undefined; }; const refs = Array.isArray(value.referenceImages) ? value.referenceImages.map(asset).filter(Boolean) : undefined; const firstFrame = asset(value.firstFrame); const lastFrame = asset(value.lastFrame); const referenceVideos = Array.isArray(value.referenceVideos) ? value.referenceVideos.map(asset).filter(Boolean) : undefined; const referenceAudios = Array.isArray(value.referenceAudios) ? value.referenceAudios.map(asset).filter(Boolean) : undefined; const count = (firstFrame ? 1 : 0) + (lastFrame ? 1 : 0) + (refs?.length ?? 0) + (referenceVideos?.length ?? 0) + (referenceAudios?.length ?? 0); const mode = firstFrame && lastFrame ? "first-last-frames" : firstFrame ? "first-frame" : refs?.length ? "references" : referenceVideos?.length ? "reference-videos" : referenceAudios?.length ? "reference-audio" : "none"; return { taskId: input.taskId, summary: { mode, count }, ...(firstFrame ? { firstFrame } : {}), ...(lastFrame ? { lastFrame } : {}), ...(refs?.length ? { referenceImages: refs } : {}), ...(referenceVideos?.length ? { referenceVideos } : {}), ...(referenceAudios?.length ? { referenceAudios } : {}) }; });
bindOperationExecute(videoRequestAccountInputCleanup, async (input, principal) => { if (principal.type !== "user") throw new OperationError("unauthenticated", "User session authentication required"); return principalRequest(principal, "/api/internal/video/account-input-cleanup", { method: "POST", body: JSON.stringify(input) }); });
bindExecute("video.generate", async (input: VideoGenerateInput, principal: Principal, ctx: OperationContext) => { if (principal.type !== "user" && principal.type !== "apiKey") throw new OperationError("unauthenticated", "User identity required"); const callbackUrl = ctx.callbacks?.videoCompletionUrl; return principalRequest(principal, "/api/internal/video/generate", { method: "POST", body: JSON.stringify({ ...input, ...(callbackUrl ? { callbackUrl } : {}) }) }); });
bindExecute("video.getStatus", async (input: { taskId: string }, principal: Principal) => { if (principal.type !== "user" && principal.type !== "apiKey") throw new OperationError("unauthenticated", "User identity required"); return principalRequest(principal, "/api/internal/video/status", { method: "POST", body: JSON.stringify(input) }); });
bindOperationExecute(videoGetGeminiOperation, async (input, principal) => { if (principal.type !== "user" && principal.type !== "apiKey") throw new OperationError("unauthenticated", "User identity required"); return principalRequest(principal, "/api/internal/video/gemini/status", { method: "POST", body: JSON.stringify({ taskId: input.operationName.split("/").pop(), ...input }) }); });
